name: bmi_calc
description: A Flutter BMI Calculator App

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_gauges: ^20.4.40

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
